[target.aarch64-unknown-linux-gnu]
dockerfile = """
FROM ghcr.io/cross-rs/cross:aarch64-unknown-linux-gnu

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install -y \
        libgtk-3-dev:arm64 \
        libwebkit2gtk-4.0-dev:arm64 \
        libssl-dev:arm64 \
        libudev-dev:arm64 \
        pkg-config \
        build-essential

ENV PKG_CONFIG_ALLOW_CROSS=1
ENV PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig
ENV PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig
"""