name: Build ARM64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-tauri:
    permissions:
      contents: read
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Build ARM64 binary using Docker
        run: |
          docker run --rm -v $PWD:/workspace -w /workspace \
            --platform linux/amd64 \
            ghcr.io/cross-rs/cross:aarch64-unknown-linux-gnu \
            bash -c "
              apt-get update && 
              apt-get install -y curl build-essential &&
              curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&
              source ~/.cargo/env &&
              rustup target add aarch64-unknown-linux-gnu &&
              cd src-tauri &&
              cargo build --target aarch64-unknown-linux-gnu --release
            "

      - name: Upload ARM64 binary
        uses: actions/upload-artifact@v4
        with:
          name: batak-tauri-arm64
          path: src-tauri/target/aarch64-unknown-linux-gnu/release/batak-tauri