name: Build ARM64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-tauri:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libssl-dev libudev-dev
          
      - name: Add ARM64 architecture
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update

      - name: Install ARM64 dependencies
        run: |
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Build Rust for ARM64
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
        run: |
          cd src-tauri
          cargo build --target aarch64-unknown-linux-gnu --release

      - name: Upload ARM64 binary
        uses: actions/upload-artifact@v4
        with:
          name: batak-tauri-arm64
          path: src-tauri/target/aarch64-unknown-linux-gnu/release/batak-tauri